language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: wDxDQs8xjYVUybRwrnBegLXw+7SuP9LkD6XFo3WxVR84SZu1Mnm7PbHDvA8ZHYp4R6q9WYl+U3/AoGYlgOBkxhNKPgOmMjiMLdVwABVRLOgF46974lXxBUd6cDHMxr89B8L8jnmm0hKz3OAaZCH4vux7iYCfOCsaw5HTc0Jeofwrd//Yh7q0mQzi5F/IfUvhctOxlfxcM6eioSpntF4D43ZLA7EOHUoh//tmZoSONHI4O66/3MeY6Wh7EZrpp/D57xHSGN9Qm83tYOzIjeSL65f4sUj4ryHn9EiR1CTV7jkrZU6u6FPmrH2fsk6LTUQ1Z2iM+mA9GzRYADG8y+nweUnFGEdsOmqUeD7yGjSiSPX4eEzvAxz3t8izxxoLQMD8VrPytNSuCMWn9Pf2v14YPN01UnKwFE/ZATxwZNKLVtonXOz2E5k3KxlDKu9zP5arVqpgik8TP6fUUP2lMa7C90m2ak+c1p997oy/zxMJqQo0v/GRfv41N3TGCXTEbctJjRBwQs7SkQOMEhmEnLYY7v3hSV5rIhk2pdlWbv9YgS4utO5j6C0ht/3zBIAx+orz9j6FWUbb5CT/wQ6Dsx7jqM5eUReTbGuRFCF17VDZ1J59CLN0KCdH/EH2BZax93v3LIuAYLh1Q/Lbonzk4rLVqQSDl7GSR5JPiOgHIMjkQ0Q=
  - secure: n+JnUm2Kx70QN04OEbxa5W06sZ7qjDoyRH658iNVY304svn/ruah1r4fFarb8oaLm3+qIOxkGul7JGo/Pvh2agbyD+pRtCkaa8ZZt4zdUpbwLwpZIdj7S9YtuwqWfTYUxnm4I0eqyKdIyfFPQ9rZsjSdjaHN56b8di+f1Gh70HJWM1iU/VB8LQAN+/ktxTCJA0tZWSlzYpo5q4Q05KTe3sDK497BEJtCmGvA5p+dMS8UEYvnFc1/B2gGkWeA9EPj2KoVpClZeP9WTlN8znDTv20GH8nwj36RsBCtIQlpxVB0IUv7rfjV9a9tSinqba0vdYGxKt99DZQROQsIfUo+TuElZvEoxND93u7H5rTFNlsUpwmrnL4ppbsV9h5/cvy7m21LvYV+EmhNncMDUe77i9B50zSGgB9vD0r9TSvDklmalfz3Z/O15h1XlOiwCds5hSkPoPp9kI8DnixsxpDqPLwSdC83y8c/IaAI+TV9JYlW7OlKPRshHmgn1m4STl8zuGwTQgHFhillTX6DfcAKTa6xVjGY8D8BIxo5KYNb3mBk+3A4jgg6CaJCal2i/uUY7iglXv/ZJDcxbyjwSQN7E45YF/Yn2YvO/O/iv/A3TCSbIPMacsdpZgqXysbyw3iphnkuLA1VETzeVLAsnFKsYscfSYxZHBrNQ8++GVERqL0=
  - secure: BwLF5IXHWfOTkhcvtRIQhmySVgn24ZoAaw/MqYf9LRKJ1IoqLEmm4Ox0K8+4NUmYfg3UtCg+Q/X74ehyJ3NSmWrUc4OR+b9KHVfhSdp2uqFSegQRt8AtK1WnmYYVtqUOWLvAIzzix9mePVSxm6GC6sg5MIJmxIBHFnxNN6i+1kXwyAxL4mLpoSuEQYLMNtapvmplCe0HpjYEAN1MBQm2j10RwWJIS9mV+TwRV8mjPQ6CiNr0Ailob9MndTpIm9Nq/E6eT7w+ZyKOMd8r/0xe4vvccPU3Xa8Mdbjrcb+TRFw0SKr6ObkY7K6ytwQ5ovkf12SyF4zYMCstbrm8eGVkp5RmPqF+yok6CSwA+lQQa60PbHYf9K785J/kEraontTm/8ksBtDcO6cYMOXf94+bXo0DUAgFnyp5IswZM86365nJbvK72qymvlQ2oghUKsNmkrcxEwB/dBEFz6+tnqa6648ecWCEHaawfvi1IfjQSbfnKNRHiWKT1M5T8LcKiUwzZ/yPbVG2jnT+yTdNrcDfRRCgiFgWnbmWdKUf+0fNSbKyCSs9yttiLnZ9qyxxSyNE5tYBESYvMnbbMgAMUsldn+BJPE8ixPzBjQUZtUaCnvbM0rqS13U4tWFT/ivsrltlLEOwFbygzXvcMiGyvZu/7SUjpBd1hMiK9Vsp6ECDXHo=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_d80a2d296111_key -iv $encrypted_d80a2d296111_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
