language: python
python:
- '3.6'
install:
- pip install ansible==2.9.6 molecule molecule-gce apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/service_account.json"
  global:
  - secure: "EppbjMt5VpeiZ4NyZtY8ZshWXT4bKw2FE5CS9X13AflXOvpcsaMJ9RSx2G62qxTRIGFcOtL2rysPfp3IRbvTYd00vhBucehju3JB+bB9tP+DmbfAkED8HaDoNq/7/b8Mgf+EWz+2ZkziUujzE9qxQpoO53VfF4Ic7v4iMPi49F0wM549E4asiFco6YSwqh1gy4NZTGsA/pdpLUc/mthjIa50ir7/n1Zaj2DyeFcQ/Qfh9VP8GQe0nDN6Fnq0q1/1ZU6KEjCG8jQmhhkuXIbdzVGs+l9xCEjbUC3ixJMeIBIBklSaZcJmU/dVlWOaGgRXo4PHnGIpifXjJWYbqRODyJNwp5o0ySgi6du2z9zENOCFS+kIk4TBPuhpzw3MfOpXCd5H5AtoxH7QF1yxPwB02bx97t2SB1XThEASStBZMpjJHZI6/pJkyinRDeBadOAa+uaG1KOGNCcJ3hpuXsaXyhMU45v9IPgtAA2X6UQY5Cs4RTh17C+uEG+MI/yVsJHgoy0CnTKQihikBuAiY9kFSlawOx4f2sR5un/KnfOBv4fnBmpQc/O68in40/FeTYp5zpt1FAxFV7gv8KvTLGcLNGWL0I4W02K9dRtm7xUu39rLDovoQrvC9peb1iL18cjC2hgHFML3EZ5cVeJ/J2GvMd9999wMa3aaJ1b335hpGM4="
  - secure: "pkvCkb5qhePlhxKkFwzbudgNRylYVG39BdQSTL29D9hk2YAJIOfBqzzKjBvzqbfZyo+kM3qe1T7Tt76Q6kcCP5iY0zLXWggJw5mN1hbYuQPzPSaiDveOzW6BjgEjS2M9Cw3/dEHPYCMq3IMPz5hi0qUzz5jYY6KeNv3lfmuq1XwHobvmi4nsZWQlxwhQ9jZlWJZLpebBtf0VXCUNbyrNEI0r3QG+Qe52Vn/MHJvVDI/+m2w0U56SCl0GyBeEHke6q49pmciwmCavYSg15K70LXV1rdG6drg56/6LK2vsTCLx3YaXN6vMh9pEiN80D2RrDl67PWgzcR0RvuPInwR+EXH9xva2JDd387PcTOpmIwD8kVV0XTHicjMep1yQ9ZilFxiqBr8XJBz5FX9w7iwMnwS/Gu8Uvu1HkdsIc+XCKvsaRFmPVseudjdizhxUj1a+C84YFGpUnUug6eCy46OMkPDfDURD0EwqrEM2tNfPjUgnC1i+QV2XxXXzQkvIuTQhn1aRhrP1Doxe58zKzJxGZW73NloYoAozjQcDLFdihOPRcYqnUXBz49krzUkssSsE+frN3MOt2XslGT/PYiknKPpAMd1AkipRF7QIthThITYlXpTWIbslP/ZgMcyiSj3JlGaLKYrIwY8Zl5ImA92W7k8L0B93EzvddzdWLWwN6XU="
  - secure: "dSijYUulG6DolSWvGLi+ejX30/b6NH6uttzHv8QpoukHkeEZ7CEtaEF9UxfJk36E6t0z9sCNJuBEMLI5Zlu5HQ4GxGuvNYOBhDZdLKNRi28tKxiAhQcLU8ZzU5wPlR5rXFa5xXvd9apGiS34IduKYPgduUnJ7vl9Z9Ag+Q+rCmqPZsFhQG4Mf+cO1y7R/F6hCAl82s8hJm/WDR/N+frNKEefi6qQOX9e9h5SN3+RpT2bE7OZ1waCn/tKJszGbaV5Dg2hf3jKym5bJc4U8jc7IJu4wLkZQ+stqTEomWPvpRJyvbeq4BR8JjbKxEx9D9npIXpYttpLe1ow0WZ5xRxgLUGiSAT+iB9aX9443wXGGYYzJPgH/8WZmIOU7a80Mhva5t/PtjUSRhJsiVHmjOe5wwBrDuMhTJU5iOMtncm0x29LhF1/l7Ad9TXpZqGQz4DJm+qF/nFstW5vaKE/Q1grlInw6YqsIh4KSV89YqqwAquyIOmqE/Off67VELT63WXLDjJtxbyh4yx9txFgIRoyM6eIf9XKyYV0jtf9KNAzv6hxA2k1E+jXh/TyWnHZYUwtXeoaajRJo6KSlyWQ+OXY2DdHcnROQACdpnLn5h2ItUZKo8KxSeJe9dcdGKHt6U5lSxtqHWGNyRyIo84BDYX77HdeX9+7vprl0XtVj0oal58="
script:
- molecule list
- molecule --version
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
